spring:
  application:
    name: rivals-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 100 # 가장 많이 사용되는 값
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect

  docker:
    compose:
      file: compose-dev.yaml
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 개발 환경에서는 모든 엔드포인트를 여는 것이 편합니다.
  endpoint:
    health:
      show-details: always

riot:
  api:
    key: ${RIOT_API_KEY}
    asia-url: ${RIOT_API_ASIA_URL:https://asia.api.riotgames.com}
    kor-url: ${RIOT_API_KOR_URL:https://kr.api.riotgames.com}

logging:
  level:
    com.glennsyj.rivals: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
